# https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker

FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8-slim

# set environment variables
ENV PYTHONWRITEBYTECODE 1
ENV PYTHONBUFFERED 1
ENV PROJECT_DIR=global-api
ENV USER_NAME=appuser

# expose port
EXPOSE 8000

# copy dependencies
COPY requirements.txt .

# install dependencies
RUN pip3 install -r requirements.txt

# set working directory
WORKDIR /$PROJECT_DIR

# copy project
COPY . /$PROJECT_DIR

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
RUN useradd $USER_NAME && chown -R $USER_NAME /$PROJECT_DIR

#Switching user
USER $USER_NAME

# run command
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]